name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD      

    - name: Generate Environment Variables File for Production
      run: echo "${{secrets.PRODUCTION_ENV}}" > ./production.env


    - name: Build the Docker image
      run: docker build -t moneyb-api .
    
    - name: taging
      run: docker tag moneyb-api:latest enxxi/moneyb-api:latest
    
    - name: Push to Dockerhub
      run: docker push enxxi/moneyb-api:latest
